quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/cadastro
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  data:
    web:
      pageable:
        max-page-size: 100

  flyway:
    migrate-at-start: true

  banner:
    path: "banner.txt"
#CORS
app:
  cors:
    origins-allowed: "*"
  security:
    cors-allowed-origins: "*" # separado por vírgula


jwt:
  secret: java2021
  expiration: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

baseUrlFrontEnd: http://localhost:8081