quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/cadastro
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  data:
    web:
      pageable:
        max-page-size: 100

  flyway:
    migrate-at-start: true

  banner:
    path: "banner.txt"

  smallrye-jwt:
    enabled: true
#CORS
app:
  cors:
    origins-allowed: "*"
  security:
    cors-allowed-origins: "*" # separado por vírgula


mp:
  jwt:
    verify:
      publickey:
        location: "publickey.pem"
      issuer: "http://localhost:8080/"
# for jwt expiration duration
com:
  quarkusjwt:
    jwt:
      duration: 3000 #300 = 5min
# for user's password simulation
    password:
      secret: mysecret
      iteration: 33
      keylength: 256


baseUrlFrontEnd: http://localhost:8081

code:
  quarkus:
    modules:
      multipart:
          MultipartService/mp-rest/url: http://localhost:8080/
      multipartsesp:
          MultipartServiceSesp/mp-rest/url: https://homolog2.sesp.mt.gov.br/ws-sesp-smtc/api/preocorrencia/upload